### PR TITLE
skip the IsInternalExtension update for the vm agent namespace

### PR DESCRIPTION
**Pull request by hglkrijger**
When we publish to the agent namespace, the api is special cased to require that IsInternalExtension is set to true. Since we want to publish the agent via the extension delivery pipeline with the azure-extensions-cli, we need to allow for this special case.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@hglkrijger I think adding this check here is just going to be hacky and  it's not a concern of this CLI. I suggest this:

1. a new (optional) argument to `promote-*` subcommands, like `--mark-as-internal`?
2. pass this boolean down to a new method called `updateManifest(file, isInternal, regions)`
3. create a new function `func updateManifestIsInternal([]byte) []byte)`
4. modify `updateManifestRegions` to take `[]byte` and spit `[]byte`
5. do the file reading in `updateManifest(...)` method
6. call these `updateManifestRegions()` and `updateManifestInternal()` methods in the `updateManifest(...)`

That would be way cleaner. I think we should add `if OSTC` check to EDP; not here. Based on that, EDP can append the `--mark-as-internal[=true]` flag.

**Comment by hglkrijger** [comment]
I considered that approach and even built it halfway, but it would be propagating special knowledge up the chain unnecessarily. Today it is relatively simple, there is one namespace and based on that condition you set/unset one flag, but there may be more special cases and/or combinations to support in the future, which I think we would be better off abstracting away. 

Additionally, there really is no other way to promote. If you are publishing to that namespace, you are forced to leave the `IsInternalExtension` attribute as `true` or it will not work. In the same way we previously decided to set the attribute blindly when promoting, we can also decide when not to set it. 

This change I think makes it simpler to use the promote API, whereas providing another option (and forcing every client to know and understand it) makes things messier.

**Comment by ahmetalpbalkan** [comment]
> Additionally, there really is no other way to promote. If you are publishing to that namespace, you are forced to leave the IsInternalExtension attribute as true or it will not work. In the same way we previously decided to set the attribute blindly when promoting, we can also decide when not to set it.

I'm not arguing that this is how API works at all, I get this change should be made. My problem is about how it is done.

> Today it is relatively simple, there is one namespace

If we get the Windows agent published using this CLI as well someday, it's no surprise that this special knowledge will change again.

> whereas providing another option (and forcing every client to know and understand it) makes things messier.

I'm not sure why a command line argument, which can be documented as:

    --keep-as-internal: use this if you're publishing an agent`

 is any messier. It looks very straightforward to me.

> and forcing every client to know and understand it

I assume the agents are only going to be published by Jenkins pipeline and we have special jobs for them. It is already _specialized_ for agent publishing. They are the only ones who need to know that this argument should be added for agents.

I don't get hardcoding such a specific detail (like namespace, which is also probably subject to change or get one more) into this very generic tool which works _quite_ transparently from outside.

If someday some extension and an agent gets type collision (e.g. I don't know what windows agent uses) it will be quite troublesome to discover why this CLI is behaving weirdly on that particular namespace to an extension publisher...

I'm currently 👎  to this implementation, others can chime in.

**Comment by ahmetalpbalkan** [comment]
cc: @boumenot. I'm trying to understand if adding this special `--keep-as-internal` flag to the EDP is the right abstraction level or not (as opposed to burying this knowledge into the extensions-cli).

**Comment by boumenot** [comment]
There are only two instances where this exists, which lends credence to adding it to the code explicitly.  But, I would rather have an explicit flag that a user has to set.

**Comment by boumenot** [comment]
LGTM.

Hans and I discussed this more.  The alternatives are undesirable, and the Agent extension is treated specially.  We're going to embedded this flag in the code.

**Pull request merged**
